name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  lint-format-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm@9.14

      - name: Verify pnpm installation
        run: pnpm --version  # This will check if pnpm is installed correctly

      - name: Install dependencies
        run: pnpm install

      - name: Run typecheck
        run: pnpm typecheck

      - name: Run format check
        run: pnpm format

      - name: Run lint
        run: pnpm lint
